"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { fillDocument, uploadDocument } from "@/lib/api";
import type { DocumentDef, GeneratedDocument, SubmitResult, SubmittedDoc } from "@/lib/types";

export type DocCompany = {
  name: string;
  entity_type: string;
  jurisdiction: string;
  founderName: string;
  ein: string;
};

function docKey(code: string, name: string): string {
  return `${code}-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")}`;
}

const ENTITY: Record<string, string> = {
  "c-corp": "C-Corporation",
  "s-corp": "S-Corporation",
  llc: "LLC",
};
const JURISDICTION: Record<string, string> = { US: "Delaware" };

function resolveTemplate(
  template: string,
  company: DocCompany,
  fields: Record<string, string>,
): string {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const body = template
    .replaceAll("{{company.name}}", company.name || "—")
    .replaceAll("{{company.entity}}", ENTITY[company.entity_type] || company.entity_type || "company")
    .replaceAll("{{company.jurisdiction}}", JURISDICTION[company.jurisdiction] || company.jurisdiction)
    .replaceAll("{{company.date}}", today);
  return body.replace(/\{\{(\w+)\}\}/g, (_m, k: string) => (fields[k]?.trim() ? fields[k] : "__________"));
}

// --- Download: render the filled document to a clean, print-ready HTML file (open → Save as PDF) ---

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function inlineToHtml(text: string): string {
  return escapeHtml(text)
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>");
}

function bodyToHtml(text: string): string {
  return text
    .split("\n")
    .map((raw) => {
      const line = raw.replace(/\s+$/, "");
      if (line.trim() === "---") return "<hr/>";
      if (line.startsWith("# ")) return `<h1>${inlineToHtml(line.slice(2))}</h1>`;
      if (line.startsWith("## ")) return `<h2>${inlineToHtml(line.slice(3))}</h2>`;
      if (line.startsWith("### ")) return `<p class="eyebrow">${inlineToHtml(line.slice(4))}</p>`;
      if (line.startsWith("- ") || line.startsWith("* "))
        return `<p class="li">• ${inlineToHtml(line.slice(2))}</p>`;
      if (line.startsWith("> ")) return `<blockquote>${inlineToHtml(line.slice(2))}</blockquote>`;
      if (line.startsWith("____")) return `<pre class="sig">${escapeHtml(line)}</pre>`;
      if (line.trim() === "") return '<div class="sp"></div>';
      return `<p>${inlineToHtml(line)}</p>`;
    })
    .join("\n");
}

function downloadDoc(title: string, body: string, accent: string): void {
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
  @page { margin: 1in; }
  body { font-family: Georgia, "Times New Roman", serif; color: #1a201c; line-height: 1.55;
    max-width: 760px; margin: 40px auto; padding: 0 24px; }
  .accent { height: 4px; background: ${accent}; margin-bottom: 28px; }
  h1 { font-family: Inter, system-ui, sans-serif; font-size: 24px; letter-spacing: -0.02em; margin: 0 0 4px; }
  h2 { font-family: Inter, system-ui, sans-serif; font-size: 15px; margin: 18px 0 4px; }
  .eyebrow { font-family: Inter, system-ui, sans-serif; text-transform: uppercase; letter-spacing: .08em;
    font-size: 12px; color: #6b746c; margin: 0 0 10px; }
  p { margin: 6px 0; } .li { margin: 2px 0 2px 16px; text-indent: -12px; }
  hr { border: none; border-top: 1px solid #d9ddd6; margin: 20px 0; }
  blockquote { border-left: 3px solid ${accent}; background: #f6f8f5; margin: 12px 0; padding: 8px 14px;
    font-family: Inter, system-ui, sans-serif; font-size: 13px; }
  .sig { font-family: ui-monospace, monospace; color: #6b746c; margin-top: 24px; white-space: pre; }
  a { color: ${accent}; } .sp { height: 8px; }
  .foot { margin-top: 40px; font-family: Inter, system-ui, sans-serif; font-size: 11px; color: #9aa29a;
    border-top: 1px solid #e6e9e4; padding-top: 10px; }
</style></head>
<body><div class="accent"></div>${bodyToHtml(body)}
<p class="foot">Generated by StartupKit · Draft for review — not legal advice. Open this file and use
Print → Save as PDF, then sign.</p></body></html>`;
  const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

function Italic({ text }: { text: string }) {
  const parts = text.split("*");
  return (
    <>
      {parts.map((p, i) => (i % 2 === 1 ? <em key={i}>{p}</em> : <span key={i}>{p}</span>))}
    </>
  );
}

function fmtText(text: string) {
  // bold (**) then italic (*)
  return text
    .split("**")
    .map((seg, i) =>
      i % 2 === 1 ? (
        <strong key={i} className="font-semibold text-ink">
          {seg}
        </strong>
      ) : (
        <Italic key={i} text={seg} />
      ),
    );
}

function Inline({ text }: { text: string }) {
  // markdown links [label](url), then bold/italic
  const nodes: React.ReactNode[] = [];
  const re = /\[([^\]]+)\]\(([^)]+)\)/g;
  let last = 0;
  let m: RegExpExecArray | null;
  let k = 0;
  while ((m = re.exec(text)) !== null) {
    if (m.index > last) nodes.push(<span key={k++}>{fmtText(text.slice(last, m.index))}</span>);
    nodes.push(
      <a
        key={k++}
        href={m[2]}
        target="_blank"
        rel="noopener noreferrer"
        className="font-medium text-seal-ink underline underline-offset-2 hover:text-seal"
      >
        {m[1]}
      </a>,
    );
    last = m.index + m[0].length;
  }
  if (last < text.length) nodes.push(<span key={k++}>{fmtText(text.slice(last))}</span>);
  return <>{nodes}</>;
}

/** The one themed renderer for every document body — hand-authored template OR StartupKit draft. */
function DocBody({ text }: { text: string }) {
  const lines = text.split("\n");
  return (
    <div className="font-serif text-[13.5px] leading-relaxed text-ink-soft">
      {lines.map((raw, i) => {
        const line = raw.trimEnd();
        if (line.trim() === "---") return <hr key={i} className="my-4 border-line" />;
        if (line.startsWith("# "))
          return (
            <h2 key={i} className="font-sans text-xl font-bold tracking-tight text-ink">
              {line.slice(2)}
            </h2>
          );
        if (line.startsWith("## "))
          return (
            <h3 key={i} className="mt-3 font-sans text-sm font-bold text-ink">
              {line.slice(3)}
            </h3>
          );
        if (line.startsWith("### "))
          return (
            <h3 key={i} className="font-sans text-sm font-medium uppercase tracking-wide text-muted">
              {line.slice(4)}
            </h3>
          );
        if (line.startsWith("- ") || line.startsWith("* "))
          return (
            <p key={i} className="my-0.5 pl-4 -indent-3">
              •&nbsp;<Inline text={line.slice(2)} />
            </p>
          );
        if (line.startsWith("> "))
          return (
            <p
              key={i}
              className="my-2 rounded-r-lg border-l-2 border-fuse bg-[#F8EAE8] px-3 py-2 font-sans text-xs text-fuse"
            >
              <Inline text={line.slice(2)} />
            </p>
          );
        if (line.startsWith("____"))
          return (
            <p key={i} className="mt-5 whitespace-pre font-mono text-xs text-muted">
              {line}
            </p>
          );
        if (line.trim() === "") return <div key={i} className="h-2" />;
        return (
          <p key={i} className="my-1.5">
            <Inline text={line} />
          </p>
        );
      })}
    </div>
  );
}

async function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result));
    r.onerror = reject;
    r.readAsDataURL(file);
  });
}

export function DocumentTemplate({
  companyId,
  workflowCode,
  phaseN,
  color,
  doc,
  company,
  facts,
  submitted,
  generated,
  phaseComplete,
  onSubmitted,
}: {
  companyId: string;
  workflowCode: string;
  phaseN: number;
  color: string;
  doc: DocumentDef;
  company: DocCompany;
  facts?: Record<string, string>;
  submitted?: SubmittedDoc;
  generated?: GeneratedDocument;
  phaseComplete: boolean;
  onSubmitted: (r: SubmitResult) => void;
}) {
  const hasTemplate = Boolean(doc.template);
  const [busy, setBusy] = useState<"" | "fill" | "upload">("");
  const [done, setDone] = useState<SubmittedDoc | undefined>(submitted);
  const [fields, setFields] = useState<Record<string, string>>(() => {
    const init: Record<string, string> = { ...(submitted?.fields ?? {}) };
    for (const f of doc.fields) {
      if (init[f.key]) continue;
      // Capture once, never re-enter: pre-fill from the Company Object / Phase-0 answers.
      if (f.prefill === "founder.name") init[f.key] = company.founderName;
      else if (f.prefill === "company.ein") init[f.key] = company.ein;
      else if (facts?.[f.key]) init[f.key] = facts[f.key];
    }
    return init;
  });

  // Guided TASK: no fillable template, no generated draft, but step-by-step how-to instructions.
  const hasGuidance = !hasTemplate && !generated && Boolean(doc.guidance);
  // The modal body — one of: your fillable template, the StartupKit draft, or guided how-to steps.
  const body = hasTemplate
    ? resolveTemplate(doc.template, company, fields)
    : generated?.body ?? (hasGuidance ? resolveTemplate(doc.guidance, company, {}) : "");
  const isDone = Boolean(done) || (phaseComplete && Boolean(body && !hasGuidance));
  const [open, setOpen] = useState(false);

  // Modal: close on Escape, lock background scroll while it's open.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [open]);

  async function save() {
    setBusy("fill");
    try {
      const r = await fillDocument(companyId, {
        workflow_code: workflowCode,
        phase_n: phaseN,
        doc_name: doc.name,
        fields,
      });
      setDone({
        doc_key: docKey(workflowCode, doc.name),
        workflow_code: workflowCode,
        phase_n: phaseN,
        doc_name: doc.name,
        method: "filled",
        fields,
        filename: "",
      });
      onSubmitted(r);
    } finally {
      setBusy("");
    }
  }

  async function upload(file: File) {
    setBusy("upload");
    try {
      const content = file.size < 4_000_000 ? await fileToBase64(file) : "";
      const r = await uploadDocument(companyId, {
        workflow_code: workflowCode,
        phase_n: phaseN,
        doc_name: doc.name,
        filename: file.name,
        content_base64: content,
      });
      setDone({
        doc_key: docKey(workflowCode, doc.name),
        workflow_code: workflowCode,
        phase_n: phaseN,
        doc_name: doc.name,
        method: "uploaded",
        fields: {},
        filename: file.name,
      });
      onSubmitted(r);
    } finally {
      setBusy("");
    }
  }

  const statusLine = done
    ? done.method === "uploaded"
      ? `Uploaded · ${done.filename}`
      : "Completed"
    : isDone
      ? "Drafted by StartupKit — review & sign"
      : hasGuidance
        ? "Step-by-step guide — do it, then mark done"
        : doc.note;

  const tag = isDone
    ? null
    : hasTemplate
      ? { label: "fillable template", cls: "bg-seal-soft text-seal-ink" }
      : generated
        ? { label: "StartupKit draft", cls: "bg-teal-50 text-teal-900" }
        : hasGuidance
          ? { label: "guided steps", cls: "bg-[#E6F1FB] text-[#0A3F6E]" }
          : { label: "upload to complete", cls: "bg-paper text-muted border border-line" };

  const fieldsForm = hasTemplate && doc.fields.length > 0 && (
    <>
      <p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-muted">
        What you provide
      </p>
      <div className="mb-1 grid gap-3 sm:grid-cols-2">
        {doc.fields.map((f) => (
          <label key={f.key} className="block">
            <span className="mb-1 block text-xs font-medium text-ink-soft">{f.label}</span>
            {f.kind === "textarea" ? (
              <textarea
                className="field-input min-h-[52px] resize-none text-sm"
                value={fields[f.key] ?? ""}
                placeholder={f.placeholder}
                onChange={(e) => setFields((s) => ({ ...s, [f.key]: e.target.value }))}
              />
            ) : (
              <input
                className="field-input text-sm"
                type={f.kind === "date" ? "date" : f.kind === "number" ? "number" : "text"}
                value={fields[f.key] ?? ""}
                placeholder={f.placeholder}
                onChange={(e) => setFields((s) => ({ ...s, [f.key]: e.target.value }))}
              />
            )}
          </label>
        ))}
      </div>
    </>
  );

  const actions = (
    <div className="flex flex-wrap items-center gap-3">
      {hasTemplate && doc.fields.length > 0 && (
        <button onClick={save} disabled={busy !== ""} className="btn-primary text-sm">
          {busy === "fill" ? "Saving…" : done ? "Update & keep complete ✓" : "Save & mark complete ✓"}
        </button>
      )}
      {hasGuidance && (
        <button onClick={save} disabled={busy !== ""} className="btn-primary text-sm">
          {busy === "fill" ? "Saving…" : done ? "Done ✓" : "✓ Mark as done"}
        </button>
      )}
      {body && !hasGuidance && (
        <button
          onClick={() => downloadDoc(doc.name, body, color)}
          disabled={busy !== ""}
          className="rounded-lg border border-line bg-paper px-3.5 py-2 text-sm font-medium text-ink-soft transition hover:border-seal hover:text-seal-ink"
        >
          ⬇ Download to sign
        </button>
      )}
      <label
        className={`cursor-pointer rounded-lg border border-line bg-paper px-3.5 py-2 text-sm font-medium text-ink-soft transition hover:border-seal hover:text-seal-ink ${
          busy !== "" ? "pointer-events-none opacity-60" : ""
        }`}
      >
        {busy === "upload"
          ? "Uploading…"
          : hasGuidance
            ? "⬆ Upload proof (optional)"
            : generated && !hasTemplate
              ? "⬆ Upload signed copy"
              : "⬆ Upload your copy"}
        <input
          type="file"
          className="hidden"
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f) void upload(f);
          }}
        />
      </label>
      {done && (
        <span className="text-xs font-medium text-teal">
          ✓ Done{" "}
          {done.method === "uploaded" ? `(uploaded ${done.filename})` : hasGuidance ? "" : "(filled)"}
        </span>
      )}
    </div>
  );

  return (
    <>
      {/* compact row — click opens the document in a focused modal */}
      <button
        onClick={() => setOpen(true)}
        className={`flex w-full items-center justify-between gap-3 rounded-xl border bg-paper px-3.5 py-2.5 text-left transition hover:border-seal/50 ${
          isDone ? "border-teal/40 bg-teal-50/30" : doc.critical ? "border-fuse/40" : "border-line"
        }`}
      >
        <span className="flex min-w-0 items-center gap-2.5">
          <span className="text-sm">{isDone ? "✅" : doc.critical ? "🔴" : "📄"}</span>
          <span className="min-w-0">
            <span className="flex flex-wrap items-center gap-2">
              <span className="truncate text-sm font-medium text-ink">{doc.name}</span>
              {!doc.required && (
                <span className="font-mono text-[10px] uppercase text-muted">optional</span>
              )}
              {tag && (
                <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${tag.cls}`}>
                  {tag.label}
                </span>
              )}
            </span>
            {statusLine && (
              <span className={`block text-xs ${done ? "text-teal" : "text-muted"}`}>
                {statusLine}
              </span>
            )}
          </span>
        </span>
        <span className="shrink-0 font-mono text-xs font-semibold text-seal-ink">
          {isDone ? "View" : "Open"} →
        </span>
      </button>

      {open &&
        typeof document !== "undefined" &&
        createPortal(
          <div
            className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-ink/40 p-4 backdrop-blur-md sm:p-8"
            onClick={() => setOpen(false)}
          >
            <div
              className="my-auto w-full max-w-2xl animate-fade-up rounded-2xl border border-line bg-panel shadow-lift"
              onClick={(e) => e.stopPropagation()}
            >
              {/* header */}
              <div className="flex items-center justify-between gap-3 border-b border-line px-5 py-3.5">
                <div className="flex min-w-0 items-center gap-2">
                  <span>{isDone ? "✅" : doc.critical ? "🔴" : "📄"}</span>
                  <h3 className="truncate font-semibold text-ink">{doc.name}</h3>
                  {tag && (
                    <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${tag.cls}`}>
                      {tag.label}
                    </span>
                  )}
                </div>
                <button
                  onClick={() => setOpen(false)}
                  aria-label="Close"
                  className="rounded-lg px-2 py-1 text-muted transition hover:bg-paper hover:text-ink"
                >
                  ✕
                </button>
              </div>

              {/* scrollable body: the document + the inputs */}
              <div className="max-h-[72vh] overflow-y-auto px-5 py-4">
                {body ? (
                  <div
                    className="mb-4 rounded-xl border border-line bg-white p-6 shadow-sm"
                    style={{ borderTop: `3px solid ${color}` }}
                  >
                    <DocBody text={body} />
                  </div>
                ) : (
                  <p className="mb-3 text-sm text-ink-soft">
                    {doc.note || "Complete this document, then upload your copy to mark it done."}
                  </p>
                )}
                {fieldsForm}
              </div>

              {/* sticky footer actions */}
              <div className="border-t border-line px-5 py-3.5">{actions}</div>
            </div>
          </div>,
          document.body,
        )}
    </>
  );
}
